/// Convenience initializers building the ``ElementPair`` chains for
/// ``Row``, ``Column``, and ``Overlay`` — one overload per child
/// count, up to ``maxContainerChildren``. Nest containers for more.
///
/// Generated by Tools/gen_inits.py; edit that,
/// not this.


extension Row where Children: ~Escapable {
    @_lifetime(copy c0)
    public init<C0: Element & ~Escapable>(
        spacing: Int = 0, alignment: CrossAlignment = .start,
        _ c0: consuming C0)
    where Children == ElementPair<C0, EmptyList> {
        self.init(spacing: spacing, alignment: alignment,
                  children: ElementPair(c0, EmptyList()))
    }

    @_lifetime(copy c0, copy c1)
    public init<C0: Element & ~Escapable, C1: Element & ~Escapable>(
        spacing: Int = 0, alignment: CrossAlignment = .start,
        _ c0: consuming C0, _ c1: consuming C1)
    where Children == ElementPair<C0, ElementPair<C1, EmptyList>> {
        self.init(spacing: spacing, alignment: alignment,
                  children: ElementPair(c0, ElementPair(c1, EmptyList())))
    }

    @_lifetime(copy c0, copy c1, copy c2)
    public init<C0: Element & ~Escapable, C1: Element & ~Escapable, C2: Element & ~Escapable>(
        spacing: Int = 0, alignment: CrossAlignment = .start,
        _ c0: consuming C0, _ c1: consuming C1, _ c2: consuming C2)
    where Children == ElementPair<C0, ElementPair<C1, ElementPair<C2, EmptyList>>> {
        self.init(spacing: spacing, alignment: alignment,
                  children: ElementPair(c0, ElementPair(c1, ElementPair(c2, EmptyList()))))
    }

    @_lifetime(copy c0, copy c1, copy c2, copy c3)
    public init<C0: Element & ~Escapable, C1: Element & ~Escapable, C2: Element & ~Escapable, C3: Element & ~Escapable>(
        spacing: Int = 0, alignment: CrossAlignment = .start,
        _ c0: consuming C0, _ c1: consuming C1, _ c2: consuming C2, _ c3: consuming C3)
    where Children == ElementPair<C0, ElementPair<C1, ElementPair<C2, ElementPair<C3, EmptyList>>>> {
        self.init(spacing: spacing, alignment: alignment,
                  children: ElementPair(c0, ElementPair(c1, ElementPair(c2, ElementPair(c3, EmptyList())))))
    }

    @_lifetime(copy c0, copy c1, copy c2, copy c3, copy c4)
    public init<C0: Element & ~Escapable, C1: Element & ~Escapable, C2: Element & ~Escapable, C3: Element & ~Escapable, C4: Element & ~Escapable>(
        spacing: Int = 0, alignment: CrossAlignment = .start,
        _ c0: consuming C0, _ c1: consuming C1, _ c2: consuming C2, _ c3: consuming C3, _ c4: consuming C4)
    where Children == ElementPair<C0, ElementPair<C1, ElementPair<C2, ElementPair<C3, ElementPair<C4, EmptyList>>>>> {
        self.init(spacing: spacing, alignment: alignment,
                  children: ElementPair(c0, ElementPair(c1, ElementPair(c2, ElementPair(c3, ElementPair(c4, EmptyList()))))))
    }

    @_lifetime(copy c0, copy c1, copy c2, copy c3, copy c4, copy c5)
    public init<C0: Element & ~Escapable, C1: Element & ~Escapable, C2: Element & ~Escapable, C3: Element & ~Escapable, C4: Element & ~Escapable, C5: Element & ~Escapable>(
        spacing: Int = 0, alignment: CrossAlignment = .start,
        _ c0: consuming C0, _ c1: consuming C1, _ c2: consuming C2, _ c3: consuming C3, _ c4: consuming C4, _ c5: consuming C5)
    where Children == ElementPair<C0, ElementPair<C1, ElementPair<C2, ElementPair<C3, ElementPair<C4, ElementPair<C5, EmptyList>>>>>> {
        self.init(spacing: spacing, alignment: alignment,
                  children: ElementPair(c0, ElementPair(c1, ElementPair(c2, ElementPair(c3, ElementPair(c4, ElementPair(c5, EmptyList())))))))
    }

    @_lifetime(copy c0, copy c1, copy c2, copy c3, copy c4, copy c5, copy c6)
    public init<C0: Element & ~Escapable, C1: Element & ~Escapable, C2: Element & ~Escapable, C3: Element & ~Escapable, C4: Element & ~Escapable, C5: Element & ~Escapable, C6: Element & ~Escapable>(
        spacing: Int = 0, alignment: CrossAlignment = .start,
        _ c0: consuming C0, _ c1: consuming C1, _ c2: consuming C2, _ c3: consuming C3, _ c4: consuming C4, _ c5: consuming C5, _ c6: consuming C6)
    where Children == ElementPair<C0, ElementPair<C1, ElementPair<C2, ElementPair<C3, ElementPair<C4, ElementPair<C5, ElementPair<C6, EmptyList>>>>>>> {
        self.init(spacing: spacing, alignment: alignment,
                  children: ElementPair(c0, ElementPair(c1, ElementPair(c2, ElementPair(c3, ElementPair(c4, ElementPair(c5, ElementPair(c6, EmptyList()))))))))
    }

    @_lifetime(copy c0, copy c1, copy c2, copy c3, copy c4, copy c5, copy c6, copy c7)
    public init<C0: Element & ~Escapable, C1: Element & ~Escapable, C2: Element & ~Escapable, C3: Element & ~Escapable, C4: Element & ~Escapable, C5: Element & ~Escapable, C6: Element & ~Escapable, C7: Element & ~Escapable>(
        spacing: Int = 0, alignment: CrossAlignment = .start,
        _ c0: consuming C0, _ c1: consuming C1, _ c2: consuming C2, _ c3: consuming C3, _ c4: consuming C4, _ c5: consuming C5, _ c6: consuming C6, _ c7: consuming C7)
    where Children == ElementPair<C0, ElementPair<C1, ElementPair<C2, ElementPair<C3, ElementPair<C4, ElementPair<C5, ElementPair<C6, ElementPair<C7, EmptyList>>>>>>>> {
        self.init(spacing: spacing, alignment: alignment,
                  children: ElementPair(c0, ElementPair(c1, ElementPair(c2, ElementPair(c3, ElementPair(c4, ElementPair(c5, ElementPair(c6, ElementPair(c7, EmptyList())))))))))
    }
}

extension Column where Children: ~Escapable {
    @_lifetime(copy c0)
    public init<C0: Element & ~Escapable>(
        spacing: Int = 0, alignment: CrossAlignment = .start,
        _ c0: consuming C0)
    where Children == ElementPair<C0, EmptyList> {
        self.init(spacing: spacing, alignment: alignment,
                  children: ElementPair(c0, EmptyList()))
    }

    @_lifetime(copy c0, copy c1)
    public init<C0: Element & ~Escapable, C1: Element & ~Escapable>(
        spacing: Int = 0, alignment: CrossAlignment = .start,
        _ c0: consuming C0, _ c1: consuming C1)
    where Children == ElementPair<C0, ElementPair<C1, EmptyList>> {
        self.init(spacing: spacing, alignment: alignment,
                  children: ElementPair(c0, ElementPair(c1, EmptyList())))
    }

    @_lifetime(copy c0, copy c1, copy c2)
    public init<C0: Element & ~Escapable, C1: Element & ~Escapable, C2: Element & ~Escapable>(
        spacing: Int = 0, alignment: CrossAlignment = .start,
        _ c0: consuming C0, _ c1: consuming C1, _ c2: consuming C2)
    where Children == ElementPair<C0, ElementPair<C1, ElementPair<C2, EmptyList>>> {
        self.init(spacing: spacing, alignment: alignment,
                  children: ElementPair(c0, ElementPair(c1, ElementPair(c2, EmptyList()))))
    }

    @_lifetime(copy c0, copy c1, copy c2, copy c3)
    public init<C0: Element & ~Escapable, C1: Element & ~Escapable, C2: Element & ~Escapable, C3: Element & ~Escapable>(
        spacing: Int = 0, alignment: CrossAlignment = .start,
        _ c0: consuming C0, _ c1: consuming C1, _ c2: consuming C2, _ c3: consuming C3)
    where Children == ElementPair<C0, ElementPair<C1, ElementPair<C2, ElementPair<C3, EmptyList>>>> {
        self.init(spacing: spacing, alignment: alignment,
                  children: ElementPair(c0, ElementPair(c1, ElementPair(c2, ElementPair(c3, EmptyList())))))
    }

    @_lifetime(copy c0, copy c1, copy c2, copy c3, copy c4)
    public init<C0: Element & ~Escapable, C1: Element & ~Escapable, C2: Element & ~Escapable, C3: Element & ~Escapable, C4: Element & ~Escapable>(
        spacing: Int = 0, alignment: CrossAlignment = .start,
        _ c0: consuming C0, _ c1: consuming C1, _ c2: consuming C2, _ c3: consuming C3, _ c4: consuming C4)
    where Children == ElementPair<C0, ElementPair<C1, ElementPair<C2, ElementPair<C3, ElementPair<C4, EmptyList>>>>> {
        self.init(spacing: spacing, alignment: alignment,
                  children: ElementPair(c0, ElementPair(c1, ElementPair(c2, ElementPair(c3, ElementPair(c4, EmptyList()))))))
    }

    @_lifetime(copy c0, copy c1, copy c2, copy c3, copy c4, copy c5)
    public init<C0: Element & ~Escapable, C1: Element & ~Escapable, C2: Element & ~Escapable, C3: Element & ~Escapable, C4: Element & ~Escapable, C5: Element & ~Escapable>(
        spacing: Int = 0, alignment: CrossAlignment = .start,
        _ c0: consuming C0, _ c1: consuming C1, _ c2: consuming C2, _ c3: consuming C3, _ c4: consuming C4, _ c5: consuming C5)
    where Children == ElementPair<C0, ElementPair<C1, ElementPair<C2, ElementPair<C3, ElementPair<C4, ElementPair<C5, EmptyList>>>>>> {
        self.init(spacing: spacing, alignment: alignment,
                  children: ElementPair(c0, ElementPair(c1, ElementPair(c2, ElementPair(c3, ElementPair(c4, ElementPair(c5, EmptyList())))))))
    }

    @_lifetime(copy c0, copy c1, copy c2, copy c3, copy c4, copy c5, copy c6)
    public init<C0: Element & ~Escapable, C1: Element & ~Escapable, C2: Element & ~Escapable, C3: Element & ~Escapable, C4: Element & ~Escapable, C5: Element & ~Escapable, C6: Element & ~Escapable>(
        spacing: Int = 0, alignment: CrossAlignment = .start,
        _ c0: consuming C0, _ c1: consuming C1, _ c2: consuming C2, _ c3: consuming C3, _ c4: consuming C4, _ c5: consuming C5, _ c6: consuming C6)
    where Children == ElementPair<C0, ElementPair<C1, ElementPair<C2, ElementPair<C3, ElementPair<C4, ElementPair<C5, ElementPair<C6, EmptyList>>>>>>> {
        self.init(spacing: spacing, alignment: alignment,
                  children: ElementPair(c0, ElementPair(c1, ElementPair(c2, ElementPair(c3, ElementPair(c4, ElementPair(c5, ElementPair(c6, EmptyList()))))))))
    }

    @_lifetime(copy c0, copy c1, copy c2, copy c3, copy c4, copy c5, copy c6, copy c7)
    public init<C0: Element & ~Escapable, C1: Element & ~Escapable, C2: Element & ~Escapable, C3: Element & ~Escapable, C4: Element & ~Escapable, C5: Element & ~Escapable, C6: Element & ~Escapable, C7: Element & ~Escapable>(
        spacing: Int = 0, alignment: CrossAlignment = .start,
        _ c0: consuming C0, _ c1: consuming C1, _ c2: consuming C2, _ c3: consuming C3, _ c4: consuming C4, _ c5: consuming C5, _ c6: consuming C6, _ c7: consuming C7)
    where Children == ElementPair<C0, ElementPair<C1, ElementPair<C2, ElementPair<C3, ElementPair<C4, ElementPair<C5, ElementPair<C6, ElementPair<C7, EmptyList>>>>>>>> {
        self.init(spacing: spacing, alignment: alignment,
                  children: ElementPair(c0, ElementPair(c1, ElementPair(c2, ElementPair(c3, ElementPair(c4, ElementPair(c5, ElementPair(c6, ElementPair(c7, EmptyList())))))))))
    }
}

extension Overlay where Children: ~Escapable {
    @_lifetime(copy c0)
    public init<C0: Element & ~Escapable>(
        alignment: Alignment = .topLeading,
        _ c0: consuming C0)
    where Children == ElementPair<C0, EmptyList> {
        self.init(alignment: alignment,
                  children: ElementPair(c0, EmptyList()))
    }

    @_lifetime(copy c0, copy c1)
    public init<C0: Element & ~Escapable, C1: Element & ~Escapable>(
        alignment: Alignment = .topLeading,
        _ c0: consuming C0, _ c1: consuming C1)
    where Children == ElementPair<C0, ElementPair<C1, EmptyList>> {
        self.init(alignment: alignment,
                  children: ElementPair(c0, ElementPair(c1, EmptyList())))
    }

    @_lifetime(copy c0, copy c1, copy c2)
    public init<C0: Element & ~Escapable, C1: Element & ~Escapable, C2: Element & ~Escapable>(
        alignment: Alignment = .topLeading,
        _ c0: consuming C0, _ c1: consuming C1, _ c2: consuming C2)
    where Children == ElementPair<C0, ElementPair<C1, ElementPair<C2, EmptyList>>> {
        self.init(alignment: alignment,
                  children: ElementPair(c0, ElementPair(c1, ElementPair(c2, EmptyList()))))
    }

    @_lifetime(copy c0, copy c1, copy c2, copy c3)
    public init<C0: Element & ~Escapable, C1: Element & ~Escapable, C2: Element & ~Escapable, C3: Element & ~Escapable>(
        alignment: Alignment = .topLeading,
        _ c0: consuming C0, _ c1: consuming C1, _ c2: consuming C2, _ c3: consuming C3)
    where Children == ElementPair<C0, ElementPair<C1, ElementPair<C2, ElementPair<C3, EmptyList>>>> {
        self.init(alignment: alignment,
                  children: ElementPair(c0, ElementPair(c1, ElementPair(c2, ElementPair(c3, EmptyList())))))
    }

    @_lifetime(copy c0, copy c1, copy c2, copy c3, copy c4)
    public init<C0: Element & ~Escapable, C1: Element & ~Escapable, C2: Element & ~Escapable, C3: Element & ~Escapable, C4: Element & ~Escapable>(
        alignment: Alignment = .topLeading,
        _ c0: consuming C0, _ c1: consuming C1, _ c2: consuming C2, _ c3: consuming C3, _ c4: consuming C4)
    where Children == ElementPair<C0, ElementPair<C1, ElementPair<C2, ElementPair<C3, ElementPair<C4, EmptyList>>>>> {
        self.init(alignment: alignment,
                  children: ElementPair(c0, ElementPair(c1, ElementPair(c2, ElementPair(c3, ElementPair(c4, EmptyList()))))))
    }

    @_lifetime(copy c0, copy c1, copy c2, copy c3, copy c4, copy c5)
    public init<C0: Element & ~Escapable, C1: Element & ~Escapable, C2: Element & ~Escapable, C3: Element & ~Escapable, C4: Element & ~Escapable, C5: Element & ~Escapable>(
        alignment: Alignment = .topLeading,
        _ c0: consuming C0, _ c1: consuming C1, _ c2: consuming C2, _ c3: consuming C3, _ c4: consuming C4, _ c5: consuming C5)
    where Children == ElementPair<C0, ElementPair<C1, ElementPair<C2, ElementPair<C3, ElementPair<C4, ElementPair<C5, EmptyList>>>>>> {
        self.init(alignment: alignment,
                  children: ElementPair(c0, ElementPair(c1, ElementPair(c2, ElementPair(c3, ElementPair(c4, ElementPair(c5, EmptyList())))))))
    }

    @_lifetime(copy c0, copy c1, copy c2, copy c3, copy c4, copy c5, copy c6)
    public init<C0: Element & ~Escapable, C1: Element & ~Escapable, C2: Element & ~Escapable, C3: Element & ~Escapable, C4: Element & ~Escapable, C5: Element & ~Escapable, C6: Element & ~Escapable>(
        alignment: Alignment = .topLeading,
        _ c0: consuming C0, _ c1: consuming C1, _ c2: consuming C2, _ c3: consuming C3, _ c4: consuming C4, _ c5: consuming C5, _ c6: consuming C6)
    where Children == ElementPair<C0, ElementPair<C1, ElementPair<C2, ElementPair<C3, ElementPair<C4, ElementPair<C5, ElementPair<C6, EmptyList>>>>>>> {
        self.init(alignment: alignment,
                  children: ElementPair(c0, ElementPair(c1, ElementPair(c2, ElementPair(c3, ElementPair(c4, ElementPair(c5, ElementPair(c6, EmptyList()))))))))
    }

    @_lifetime(copy c0, copy c1, copy c2, copy c3, copy c4, copy c5, copy c6, copy c7)
    public init<C0: Element & ~Escapable, C1: Element & ~Escapable, C2: Element & ~Escapable, C3: Element & ~Escapable, C4: Element & ~Escapable, C5: Element & ~Escapable, C6: Element & ~Escapable, C7: Element & ~Escapable>(
        alignment: Alignment = .topLeading,
        _ c0: consuming C0, _ c1: consuming C1, _ c2: consuming C2, _ c3: consuming C3, _ c4: consuming C4, _ c5: consuming C5, _ c6: consuming C6, _ c7: consuming C7)
    where Children == ElementPair<C0, ElementPair<C1, ElementPair<C2, ElementPair<C3, ElementPair<C4, ElementPair<C5, ElementPair<C6, ElementPair<C7, EmptyList>>>>>>>> {
        self.init(alignment: alignment,
                  children: ElementPair(c0, ElementPair(c1, ElementPair(c2, ElementPair(c3, ElementPair(c4, ElementPair(c5, ElementPair(c6, ElementPair(c7, EmptyList())))))))))
    }
}
