#!/usr/bin/env python3
"""Generates ContainerInits.swift: arity 1..8 convenience inits for
Row, Column, and Overlay building the ElementPair cons chain."""

MAX = 8

HEADER = '''\
/// Convenience initializers building the ``ElementPair`` chains for
/// ``Row``, ``Column``, and ``Overlay`` — one overload per child
/// count, up to ``maxContainerChildren``. Nest containers for more.
///
/// Generated by Tools/gen_inits.py; edit that,
/// not this.
'''


def cons_type(k):
    t = "EmptyList"
    for i in reversed(range(k)):
        t = f"ElementPair<C{i}, {t}>"
    return t


def cons_expr(k):
    e = "EmptyList()"
    for i in reversed(range(k)):
        e = f"ElementPair(c{i}, {e})"
    return e


def overload(container, k):
    generics = ", ".join(f"C{i}: Element & ~Escapable" for i in range(k))
    lifetimes = ", ".join(f"copy c{i}" for i in range(k))
    params = ", ".join(f"_ c{i}: consuming C{i}" for i in range(k))
    if container == "Overlay":
        lead_param = "alignment: Alignment = .topLeading"
        lead_args = "alignment: alignment"
    else:
        lead_param = "spacing: Int = 0, alignment: CrossAlignment = .start"
        lead_args = "spacing: spacing, alignment: alignment"
    noun = {"Row": "row", "Column": "column", "Overlay": "overlay"}[container]
    doc = (f"/// A {noun} of one child." if k == 1
           else f"/// A {noun} of {k} children, first to last.")
    return f"""\
    {doc}
    @_lifetime({lifetimes})
    public init<{generics}>(
        {lead_param},
        {params})
    where Children == {cons_type(k)} {{
        self.init({lead_args},
                  children: {cons_expr(k)})
    }}
"""


parts = [HEADER]
for container in ("Row", "Column", "Overlay"):
    parts.append(f"\nextension {container} where Children: ~Escapable {{")
    for k in range(1, MAX + 1):
        parts.append(overload(container, k).rstrip())
        if k < MAX:
            parts.append("")
    parts.append("}")

print("\n".join(parts))
